### ISSUE TITLE
SyntaxError: Unexpected token ( in zotero-client/scripts/build.js:12

### ISSUE THREAD

**Issue by Mailaender** [zotero/zotero-build#4]
I am currently trying to package Zotero for @openSUSE, but already failed trying https://www.zotero.org/support/dev/client_coding/building_the_standalone_client locally:

```
matthias@mTower:~/Entwicklung/Zotero/zotero-client> npm i              
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN eslint-plugin-react@7.5.1 requires a peer of eslint@^3.0.0 || ^4.0.0 but none was installed.
matthias@mTower:~/Entwicklung/Zotero/zotero-client> npm run build

> zotero@5.0.0 build /home/matthias/Entwicklung/Zotero/zotero-client
> node ./scripts/build.js

/home/matthias/Entwicklung/Zotero/zotero-client/scripts/build.js:12
        (async () => {
               ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Linux 4.4.103-36-default
npm ERR! argv "/usr/bin/node6" "/usr/bin/npm-default" "run" "build"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zotero@5.0.0 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zotero@5.0.0 build script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zotero package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zotero
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zotero
npm ERR! There is likely additional logging output above.
```

Full [npm-debug.log](https://gist.github.com/Mailaender/f7377ff8a9ac2a1d4e8c270d98de540c)

**Comment by dstillman** [comment]
Upgrade to Node 8 or later

**Comment by Mailaender** [comment]
That helped. Thanks.
