### ISSUE TITLE
dir_build: FileNotFoundError

### ISSUE THREAD

**Issue by Terminal-Redux** [zotero/zotero-build#5]
Good afternoon. I've been trying to build Zotero on Windows with Git BASH. I've followed the steps at https://www.zotero.org/support/dev/client_coding/building_the_standalone_client_windows_notes and https://www.zotero.org/support/dev/client_coding/building_the_standalone_client up to step 7, where the instruction
`scripts/dir_build` 
follows. However, I keep getting this on Git BASH:

> Traceback (most recent call last):
  File "C:/Users/User/Documents/zotero-cliente/zotero-build/xpi/build_xpi", line 127, in main
    tmp_src_dir + os.sep
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\CAPSUS_01\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Using source directory of C:/Users/CAPSUS_01/Documents/zotero-cliente/zotero-client/build

Is this a problem on my end? Or is it something else? Cheers.

**Comment by dstillman** [comment]
The instructions say to use Cygwin, not Git Bash.
